# Generated by Django 5.1.5 on 2025-01-28 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('first_air_date', models.DateField()),
                ('overview', models.TextField()),
                ('poster_path', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
